version: '3'
services:

  nginx56:
    image: ${REGISTRY}protopopys/cscart-sandbox:nginx-latest-alpine3.7
    command: /bin/sh -c "envsubst '$${DOMAIN},$${CSCART_ADDRESS}' < /etc/nginx/templates/cscart.dist > /etc/nginx/conf.d/cscart.conf && cp -f /etc/nginx/templates/*.conf /etc/nginx/xtra/ && nginx-debug -g 'daemon off;'"
    environment:
      DOMAIN: ${DOMAIN}
      CSCART_ADDRESS: ${PHP56_ADDRESS}
    volumes:
      - ${CSCART_VOLUMES}:/var/www/html:rw
      - ${CSCART_SSL}:/etc/nginx/ssl
    networks:
      php56:
      external:
        ipv4_address: 172.22.0.56
    restart: always

  php56-fpm:
    image: ${REGISTRY}protopopys/cscart-sandbox:php${PHP56_VERSION}-fpm-alpine3.7
    volumes:
      - ${CSCART_VOLUMES}:/var/www/html:rw
    networks:
      internal:
      php56:
        aliases:
          - php-fpm
    restart: always

    ################################################################################

  nginx70:
    image: ${REGISTRY}protopopys/cscart-sandbox:nginx-latest-alpine3.7
    command: /bin/sh -c "envsubst '$${DOMAIN},$${CSCART_ADDRESS}' < /etc/nginx/templates/cscart.dist > /etc/nginx/conf.d/cscart.conf && cp -f /etc/nginx/templates/*.conf /etc/nginx/xtra/ && nginx-debug -g 'daemon off;'"
    environment:
      DOMAIN: ${DOMAIN}
      CSCART_ADDRESS: ${PHP70_ADDRESS}
    volumes:
      - ${CSCART_VOLUMES}:/var/www/html:rw
      - ${CSCART_SSL}:/etc/nginx/ssl
    networks:
      php70:
      external:
        ipv4_address: 172.22.0.70
    restart: always

  php70-fpm:
    image: ${REGISTRY}protopopys/cscart-sandbox:php${PHP70_VERSION}-fpm-alpine3.7
    volumes:
      - ${CSCART_VOLUMES}:/var/www/html:rw
    networks:
      internal:
      php70:
        aliases:
          - php-fpm
    restart: always

    ################################################################################

  nginx71:
    image: ${REGISTRY}protopopys/cscart-sandbox:nginx-latest-alpine3.7
    command: /bin/sh -c "envsubst '$${DOMAIN},$${CSCART_ADDRESS}' < /etc/nginx/templates/cscart.dist > /etc/nginx/conf.d/cscart.conf && cp -f /etc/nginx/templates/*.conf /etc/nginx/xtra/ && nginx-debug -g 'daemon off;'"
    volumes:
      - ${CSCART_VOLUMES}:/var/www/html:rw
      - ${CSCART_SSL}:/etc/nginx/ssl
    environment:
      DOMAIN: ${DOMAIN}
      CSCART_ADDRESS: ${PHP71_ADDRESS}
    networks:
      php71:
      external:
        ipv4_address: 172.22.0.71
    restart: always

  php71-fpm:
    image: ${REGISTRY}protopopys/cscart-sandbox:php${PHP71_VERSION}-fpm-alpine3.7
    volumes:
      - ${CSCART_VOLUMES}:/var/www/html:rw
    networks:
      internal:
      php71:
        aliases:
          - php-fpm
    restart: always

    ################################################################################

  nginx72:
    image: ${REGISTRY}protopopys/cscart-sandbox:nginx-latest-alpine3.7
    command: /bin/sh -c "envsubst '$${DOMAIN},$${CSCART_ADDRESS}' < /etc/nginx/templates/cscart.dist > /etc/nginx/conf.d/cscart.conf && cp -f /etc/nginx/templates/*.conf /etc/nginx/xtra/ && nginx-debug -g 'daemon off;'"
    volumes:
      - ${CSCART_VOLUMES}:/var/www/html:rw
      - ${CSCART_SSL}:/etc/nginx/ssl
    environment:
      DOMAIN: ${DOMAIN}
      CSCART_ADDRESS: ${PHP72_ADDRESS}
    networks:
      php72:
      external:
        ipv4_address: 172.22.0.72  
    restart: always

  php72-fpm:
    image: ${REGISTRY}protopopys/cscart-sandbox:php${PHP72_VERSION}-fpm-alpine3.7
    volumes:
      - ${CSCART_VOLUMES}:/var/www/html:rw
    networks:
      internal:
      php72:
        aliases:
          - php-fpm
    restart: always

################################################################################

  proxy:
    image: ${REGISTRY}protopopys/cscart-sandbox:nginx-latest-alpine3.7
    command: /bin/sh -c "envsubst '$${PHP72_ADDRESS},$${PHP71_ADDRESS},$${PHP70_ADDRESS},$${PHP56_ADDRESS},$${DOMAIN}' < /etc/nginx/templates/proxy.dist > /etc/nginx/conf.d/proxy.conf && cp -f /etc/nginx/templates/*.conf /etc/nginx/xtra/ && nginx-debug -g 'daemon off;'"
    volumes:
      - ${CSCART_SSL}:/etc/nginx/ssl
    environment:
      DOMAIN: ${DOMAIN}
      PHP72_ADDRESS: ${PHP72_ADDRESS}
      PHP71_ADDRESS: ${PHP71_ADDRESS}
      PHP70_ADDRESS: ${PHP70_ADDRESS}
      PHP56_ADDRESS: ${PHP56_ADDRESS}
    ports:
      - "80:80"
      - "443:443"
    networks:
      - external  
    restart: always

  mysql:
    image: mysql:5.7.22
    command: mysqld --sql-mode="NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION" --character_set_server="utf8" --character_set_filesystem="utf8" --collation-server="utf8_general_ci" --init-connect='SET NAMES utf8' --init_connect='SET collation_connection = utf8_general_ci' --skip-character-set-client-handshake
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_RPASS}
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASS}
    volumes:
      - ${MYSQL_LOGS}:/var/log:rw
      - ${MYSQL_DATA}:/var/lib/mysql:rw
      - ${MYSQL_CONF}:/etc/mysql/conf.d:ro
    networks:
      internal:
        aliases:
          - database

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    restart: always
    networks:
      internal:

################################################################################
networks:
  external:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 172.22.0.0/24

  internal:
    driver: bridge
  php56:
    driver: bridge
  php70:
    driver: bridge
  php71:
    driver: bridge
  php72:
    driver: bridge